#-----------log------------
logging:
  config: classpath:logback-spring.xml
#----------web container---------
server:
  port: 8080
  servlet:
    context-path: /tpm
#--------spring--------
spring:
  datasource:
    name: dataSource
    url: jdbc:mysql://192.168.0.60:3306/tpm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  #-------------mvc--------------
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  data:
    mongodb:
      host: 192.168.0.60
      port: 27017
      database: flash
#---------------mybatis--------------
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
#---------------pagehelper-------------- 
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql